"""add subscription fields to user

Revision ID: 1d1ce2791ff4
Revises: fdde9e236db8
Create Date: 2026-04-11 02:21:00.353493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1ce2791ff4'
down_revision: Union[str, Sequence[str], None] = 'fdde9e236db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sa.String(length=20), server_default='trial', nullable=False))
    op.add_column('users', sa.Column('trial_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_product_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_product_id')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'trial_start_date')
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###
