"""add password_hash and phone_number to users

Revision ID: 2e4cc268161d
Revises: 31de7f1a2e4e
Create Date: 2026-03-23 15:11:19.304794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4cc268161d'
down_revision: Union[str, Sequence[str], None] = '31de7f1a2e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_user_pet'), table_name='embeddings', postgresql_where='(pet_id IS NOT NULL)')
    op.drop_index(op.f('ix_embeddings_user_source'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_vector'), table_name='embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'password_hash')
    op.create_index(op.f('ix_embeddings_vector'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_embeddings_user_source'), 'embeddings', ['user_id', 'source_type'], unique=False)
    op.create_index(op.f('ix_embeddings_user_pet'), 'embeddings', ['user_id', 'pet_id'], unique=False, postgresql_where='(pet_id IS NOT NULL)')
    # ### end Alembic commands ###
