"""add pet profile json

Revision ID: 33baf40cf60d
Revises: accf1fbbd054
Create Date: 2026-03-19 22:30:38.017505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33baf40cf60d'
down_revision: Union[str, Sequence[str], None] = 'accf1fbbd054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'profile')
    # ### end Alembic commands ###
