"""add image_urls to chat messages

Revision ID: 426f14a464eb
Revises: 03dca5deae9b
Create Date: 2026-03-25 02:35:39.398022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426f14a464eb'
down_revision: Union[str, Sequence[str], None] = '03dca5deae9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'image_urls')
    # ### end Alembic commands ###
