"""add pet_ids json to calendar_events

Revision ID: 59c1672d0286
Revises: 5acf90bfb617
Create Date: 2026-03-23 15:38:45.626188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c1672d0286'
down_revision: Union[str, Sequence[str], None] = '5acf90bfb617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('calendar_events', sa.Column('pet_ids', sa.JSON(), server_default='[]', nullable=False))
    # Backfill: copy existing pet_id into pet_ids array
    op.execute("""
        UPDATE calendar_events
        SET pet_ids = json_build_array(pet_id::text)
        WHERE pet_id IS NOT NULL AND pet_ids::text = '[]'
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'pet_ids')
    # ### end Alembic commands ###
