"""make calendar_event pet_id nullable

Revision ID: 5acf90bfb617
Revises: 2e4cc268161d
Create Date: 2026-03-23 15:26:53.777888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acf90bfb617'
down_revision: Union[str, Sequence[str], None] = '2e4cc268161d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'pet_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'pet_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
