"""add pet profile_md

Revision ID: 93096dfcaafa
Revises: 59c1672d0286
Create Date: 2026-03-23 16:09:09.441009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93096dfcaafa'
down_revision: Union[str, Sequence[str], None] = '59c1672d0286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('profile_md', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'profile_md')
    # ### end Alembic commands ###
