"""add_rag_tables

Revision ID: dd97e66df9e4
Revises: 33baf40cf60d
Create Date: 2026-03-22 14:12:49.717135

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd97e66df9e4'
down_revision: Union[str, Sequence[str], None] = '33baf40cf60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_date', name='uq_daily_summaries_user_date')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('chat_turn', 'daily_summary', 'calendar_event', name='sourcetype'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # HNSW index for fast approximate nearest neighbor search
    op.execute("""
        CREATE INDEX ix_embeddings_vector ON embeddings
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)

    # Filter indexes
    op.create_index('ix_embeddings_user_source', 'embeddings', ['user_id', 'source_type'])
    op.create_index(
        'ix_embeddings_user_pet', 'embeddings', ['user_id', 'pet_id'],
        postgresql_where=sa.text('pet_id IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_user_pet', table_name='embeddings')
    op.drop_index('ix_embeddings_user_source', table_name='embeddings')
    op.execute('DROP INDEX IF EXISTS ix_embeddings_vector')
    op.drop_table('embeddings')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
