"""add save fields to chat_session

Revision ID: f1eb8c33c5c1
Revises: 300c4a62b62a
Create Date: 2026-04-11 22:56:13.866160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1eb8c33c5c1'
down_revision: Union[str, Sequence[str], None] = '300c4a62b62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_saved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('chat_sessions', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('chat_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'expires_at')
    op.drop_column('chat_sessions', 'title')
    op.drop_column('chat_sessions', 'is_saved')
    # ### end Alembic commands ###
