"""add location fields to calendar_events

Revision ID: f82870be7b33
Revises: b1c2d3e4f5a6
Create Date: 2026-03-28 01:52:07.314696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82870be7b33'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('location_name', sa.String(length=300), nullable=True))
    op.add_column('calendar_events', sa.Column('location_address', sa.String(length=500), nullable=True))
    op.add_column('calendar_events', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('calendar_events', sa.Column('location_lng', sa.Float(), nullable=True))
    op.add_column('calendar_events', sa.Column('place_id', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'place_id')
    op.drop_column('calendar_events', 'location_lng')
    op.drop_column('calendar_events', 'location_lat')
    op.drop_column('calendar_events', 'location_address')
    op.drop_column('calendar_events', 'location_name')
    # ### end Alembic commands ###
